# Generated by Django 4.0.5 on 2022-09-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_stack_developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='', max_length=100)),
                ('Qualification', models.CharField(max_length=50)),
                ('competence', models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='', max_length=100)),
                ('city', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
